FROM ubuntu:18.04

RUN apt-get update  \
    && apt-get install curl git make ca-certificates python3.8 python3-pip wget gfortran cmake -y

RUN cd /home \
    && git clone https://github.com/eusojk/dssat-base-files \
    && git clone -b develop https://github.com/DSSAT/dssat-csm-os \
    && cd /home/dssat-csm-os \
    && mkdir build \
    && cd build  \
    && cmake -DCMAKE_INSTALL_PREFIX=/home/dssat-base-files -DCMAKE_BUILD_TYPE=RELEASE ..  \
    && make  \
    && make install \
    && cd /home/dssat-base-files \
    && cp dscsm047 DSCSM047.EXE 

RUN mkdir -p /home/ET_DSS_HIST/dssat_files_dir  
RUN mkdir -p /home/ET_DSS_HIST/data  
RUN cp -r /home/dssat-base-files/* /home/ET_DSS_HIST/dssat_files_dir 

COPY . /home/ET_DSS_HIST/  
COPY ./TEST/* /home/ET_DSS_HIST/dssat_files_dir/ 

WORKDIR /home/ET_DSS_HIST/

RUN python3.8 -m pip install -r requirements.txt

CMD ["python3.8", "app.py"]