from app import app

from apps.ethiopia import about as ETabout
from apps.ethiopia import historical as EThistorical
from apps.ethiopia import forecast as ETforecast
from apps.ethiopia import forecast_FResampler as ETforecastFResampler
from apps.ethiopia import forecast_WGEN as ETforecastWGEN

# from apps.senegal import about as SNabout
# from apps.senegal import historical as SNhistorical
# from apps.senegal import forecast as SNforecast
# from apps.senegal import forecast_FResampler as SNforecastFResampler
# from apps.senegal import forecast_WGEN as SNforecastWGEN

# from apps.colombia import about as COabout
# from apps.colombia import historical as COhistorical
# from apps.colombia import forecast as COforecast
# from apps.colombia import forecast_FResampler as COforecastFResampler
# from apps.colombia import forecast_WGEN as COforecastWGEN

apps = {
  "ethiopia": { 
    "logo": app.get_asset_url("ethioagroclimate.png"),
    "tutorial": "https://sites.google.com/iri.columbia.edu/simagri-ethiopia/simagri-tutorial",
    "feedback": "https://sites.google.com/iri.columbia.edu/simagri-ethiopia/user-feedback-survey-form",
    "paths": {
      "/about": ETabout.layout,
      "/historical": EThistorical.layout, 
      "/forecast": ETforecast.layout,
      "/forecast-rs": ETforecastFResampler.layout,
      "/forecast-wg": ETforecastWGEN.layout,
    },
    "currency": "ETB",
    "form": { # TODO: fill in with choices
      "historical": {
        "scenario",
        "w_station",
        "crop",
        "cultivar",
        "start_y",
        "end_y",
        "target_y",
        "soil_type",
        "soil_h2o_ini",
        "soil_no3_ini",
        "planting_date",
        "planting_density",
        "fertilizer_sim",
        "fd1",
        "fN1",
        "fd2",
        "fN2",
        "fd3",
        "fN3",
        "fd4",
        "fN4",
        "irrigation_sim",
        # On reported dates
        "irrigation_method",
        "id1",
        "imm1",
        "id2",
        "imm2",
        "id3",
        "imm3",
        "id4",
        "imm4",
        "id5",
        "imm5",
        # Automatic
        "auto_i_soil_depth",
        "auto_i_threshold",
        "auto_i_efficiency",
        "enterprise_budgeting_sim",
        "crop_price",
        "fertilizer_cost",
        "seed_cost",
        "irrigation_costs",
        "fixed_costs",
        "variable_costs",
        "add_scenario",
        "scenario_table",
        "import_button",
        "download_button",
        "import_error",
        "download_error",
        "growing_period",
        "run_scenarios",
      },
    }
  },
  # "senegal":  { 
  #   "logo": app.get_asset_url("IRI_ISRA_senegal.gif"),
  #   "tutorial": "https://sites.google.com/iri.columbia.edu/simagri-senegal/simagri-tutorial",
  #   "feedback": "https://sites.google.com/iri.columbia.edu/simagri-senegal/user-feedback-survey-form",
  #   "paths": {
  #     "/about": SNabout.layout,
  #     "/historical": SNhistorical.layout, 
  #     "/forecast": SNforecast.layout,
  #     "/forecast-rs": SNforecastFResampler.layout,
  #     "/forecast-wg": SNforecastWGEN.layout,
  #   },
  #   "currency": "???",
  # },
  # "colombia": { 
  #   "logo": app.get_asset_url("SIMAGRI_CO_logo.GIF"), 
  #   "tutorial": "https://sites.google.com/iri.columbia.edu/simagri-colombia/home",
  #   "feedback": "https://sites.google.com/iri.columbia.edu/simagri-colombia/user-feedback-survey-form",
  #   "paths": {
  #     "/about": COabout.layout, 
  #     "/historical": COhistorical.layout, 
  #     "/forecast": COforecast.layout,
  #     "/forecast-rs": COforecastFResampler.layout,
  #     "/forecast-wg": COforecastWGEN.layout,
  #   },
  #   "currency": "???",
  # },
}

simagri_variables = {
    "scenario_form": {
        "historical": [
            "scenario",
            "w_station",
            "crop",
            "cultivar",
            "start_y",
            "end_y",
            "target_y",
            "soil_type",
            "soil_h2o_ini",
            "soil_no3_ini",
            "planting_date",
            "planting_density",
            "fertilizer_sim",
            "fd1",
            "fN1",
            "fP1",
            "fK1",
            "fd2",
            "fN2",
            "fP2",
            "fK2",
            "fd3",
            "fN3",
            "fP3",
            "fK3",
            "fd4",
            "fN4",
            "fP4",
            "fK4",
            "phosphorous_sim",
            "phosphorous_amt",
            "irrigation_sim",
            # On reported dates
            "irrigation_method",
            "id1",
            "imm1",
            "id2",
            "imm2",
            "id3",
            "imm3",
            "id4",
            "imm4",
            "id5",
            "imm5",
            # Automatic
            "auto_i_soil_depth",
            "auto_i_threshold",
            "auto_i_efficiency",
            "enterprise_budgeting_sim",
            "crop_price",
            "fertilizer_cost",
            "seed_cost",
            "irrigation_costs",
            "fixed_costs",
            "variable_costs",
            "add_scenario",
            "scenario_table",
            "import_button",
            "download_button",
            "import_error",
            "download_error",
            "growing_period",
            "run_scenarios",
        ],
        "forecast_rs": [
            "scenario",
            "w_station",
            "first_trimester",
            "AN1",
            "BN1",
            "AN2",
            "BN2",
            "crop",
            "cultivar",
            "soil_type",
            "soil_h2o_ini",
            "soil_no3_ini",
            "planting_date",
            "planting_density",
            "fertilizer_sim",
            "fd1",
            "fN1",
            "fP1",
            "fK1",
            "fd2",
            "fN2",
            "fP2",
            "fK2",
            "fd3",
            "fN3",
            "fP3",
            "fK3",
            "fd4",
            "fN4",
            "fP4",
            "fK4",
            "phosphorous_sim",
            "phosphorous_amt",
            "irrigation_sim",
            # On reported dates
            "irrigation_method",
            "id1",
            "imm1",
            "id2",
            "imm2",
            "id3",
            "imm3",
            "id4",
            "imm4",
            "id5",
            "imm5",
            # Automatic
            "auto_i_soil_depth",
            "auto_i_threshold",
            "auto_i_efficiency",
            "enterprise_budgeting_sim",
            "crop_price",
            "fertilizer_cost",
            "seed_cost",
            "irrigation_costs",
            "fixed_costs",
            "variable_costs",
            "add_scenario",
            "scenario_table",
            "import_button",
            "download_button",
            "import_error",
            "download_error",
            "run_scenarios",
        ],
        "forecast_wg": [
            "scenario",
            "w_station",
            "first_trimester",
            "AN1",
            "BN1",
            "AN2",
            "BN2",
            "crop",
            "cultivar",
            "soil_type",
            "soil_h2o_ini",
            "soil_no3_ini",
            "planting_date",
            "planting_density",
            "fertilizer_sim",
            "fd1",
            "fN1",
            "fP1",
            "fK1",
            "fd2",
            "fN2",
            "fP2",
            "fK2",
            "fd3",
            "fN3",
            "fP3",
            "fK3",
            "fd4",
            "fN4",
            "fP4",
            "fK4",
            "phosphorous_sim",
            "phosphorous_amt",
            "irrigation_sim",
            # On reported dates
            "irrigation_method",
            "id1",
            "imm1",
            "id2",
            "imm2",
            "id3",
            "imm3",
            "id4",
            "imm4",
            "id5",
            "imm5",
            # Automatic
            "auto_i_soil_depth",
            "auto_i_threshold",
            "auto_i_efficiency",
            "enterprise_budgeting_sim",
            "crop_price",
            "fertilizer_cost",
            "seed_cost",
            "irrigation_costs",
            "fixed_costs",
            "variable_costs",
            "add_scenario",
            "scenario_table",
            "import_button",
            "download_button",
            "import_error",
            "download_error",
            "run_scenarios",
        ],
    },
    "scenario_graphs": {
        "historical": [
            "yield_boxplots",
            "yield_excedance_curves",
            "yield_time_series",
            "yield_excedance_curves_dry",
            "yield_excedance_curves_normal",
            "yield_excedance_curves_wet",
        ],
        "forecast_rs": [
            "yield_boxplots",
            "yield_excedance_curves",
            "selected_scenario",
            "selected_yield_excedance",
            "selected_trimester_1",
            "selected_trimester_2",
        ],
        "forecast_wg": [
            "yield_boxplots",
            "yield_excedance_curves",
            "selected_scenario",
            "selected_yield_excedance",
            "selected_trimester_1",
            "selected_trimester_2",
        ],
    },
    "simulated_yield_csv": {
        "historical": [
            "dl_all_csv",
            "dl_sim_yield",
            "dl_prob_exceedance",
            "dl_seasonal_rain",
            "csv_table",
        ],
        "forecast_rs": [
            "dl_all_csv",
            "dl_sim_yield",
            # "dl_prob_exceedance",
            # "dl_seasonal_rain",
            "csv_table",
        ],
        "forecast_wg": [
            "dl_all_csv",
            "dl_sim_yield",
            # "dl_prob_exceedance",
            # "dl_seasonal_rain",
            "csv_table",
        ],
    },
    "eb_graphs": {
        "historical": [
            "eb_multiplier",
            "eb_display_graphs_button"
            "gross_margin_boxplots",
            "gross_margin_exceedance",
            "gross_margin_time_series",
        ],
        "forecast_rs": [
            "eb_multiplier",
            "eb_display_graphs_button"
            "gross_margin_boxplots",
            "gross_margin_exceedance",
        ],
        "forecast_wg": [
            "eb_multiplier",
            "eb_display_graphs_button"
            "gross_margin_boxplots",
            "gross_margin_exceedance",
        ],
    },
    "eb_simulated_yield_csv": {
        "historical": [
            "eb_dl_all_csv",
            # "eb_dl_sim_yield",
            # "eb_dl_prob_exceedance",
            # "eb_dl_seasonal_rain",
            "csv_table",
        ],
        "forecast_rs": [
            "eb_dl_all_csv",
            # "eb_dl_sim_yield",
            # "eb_dl_prob_exceedance",
            # "eb_dl_seasonal_rain",
            "csv_table",
        ],
        "forecast_wg": [
            "eb_dl_all_csv",
            # "eb_dl_sim_yield",
            # "eb_dl_prob_exceedance",
            # "eb_dl_seasonal_rain",
            "csv_table",
        ],
    },
}